import type { Model, ModelType, SpeedRating } from '@/types'

export type CatalogStatus =
  | 'default'
  | 'latest'
  | 'stable'
  | 'preview'
  | 'snapshot'
  | 'legacy'
  | 'deprecated'
  | 'recommended'

export type IntegrationStatus = 'native' | 'config_only' | 'catalog_only'

export interface OfficialModelCatalogItem {
  name: string
  model_key: string
  type: ModelType
  provider: string
  provider_label: string
  catalog_status: CatalogStatus
  integration_status: IntegrationStatus
  speed_rating: SpeedRating
  capability_tags: string[]
  description: string
  source_url: string
  source_label: string
  api_endpoint?: string
  context_window?: number
  input_price?: number
  output_price?: number
  cost_per_unit?: number
  unit?: string
  max_resolution?: string
  supported_ratios?: string[]
  supports_consistency?: boolean
  consistency_method?: Model['consistency_method']
  video_mode?: Model['video_mode']
  priority?: number
  runtime_alias?: string
}

const OPENAI_MODELS_URL = 'https://developers.openai.com/api/docs/models'
const OPENAI_ALL_MODELS_URL = 'https://developers.openai.com/api/docs/models/all'
const OPENAI_SORA_URL = 'https://developers.openai.com/api/docs/models/sora-2'
const OPENAI_REALTIME_URL = 'https://developers.openai.com/api/docs/models/gpt-realtime'
const OPENAI_TTS_URL = 'https://developers.openai.com/api/docs/models/gpt-4o-mini-tts'

const ANTHROPIC_MODELS_URL = 'https://platform.claude.com/docs/en/about-claude/models/overview'

const DEEPSEEK_MODELS_URL = 'https://api-docs.deepseek.com/api/list-models'
const DEEPSEEK_PRICING_URL = 'https://api-docs.deepseek.com/quick_start/pricing/'

const DASHSCOPE_TEXT_URL = 'https://help.aliyun.com/zh/model-studio/compatibility-of-openai-with-dashscope'
const DASHSCOPE_VISION_URL = 'https://help.aliyun.com/zh/model-studio/qwen-vl-compatible-with-openai'
const DASHSCOPE_MODELS_URL = 'https://help.aliyun.com/zh/model-studio/models'
const DASHSCOPE_TTS_URL = 'https://help.aliyun.com/zh/model-studio/text-to-speech'

const ELEVENLABS_MODELS_URL = 'https://elevenlabs.io/docs/models/'
const ELEVENLABS_API_MODELS_URL = 'https://elevenlabs.io/docs/api-reference/models/list'

const KLING_MODELS_URL = 'https://app.klingai.com/global/'
const COMFYUI_URL = 'https://github.com/comfyanonymous/ComfyUI'

const defaultPriority = (status: IntegrationStatus, catalogStatus: CatalogStatus) => {
  const base = status === 'native' ? 90 : status === 'config_only' ? 60 : 30
  switch (catalogStatus) {
    case 'default':
    case 'recommended':
      return base + 8
    case 'latest':
    case 'stable':
      return base + 5
    case 'preview':
      return base + 2
    case 'legacy':
    case 'deprecated':
      return base - 10
    default:
      return base
  }
}

export function buildModelPayloadFromCatalog(item: OfficialModelCatalogItem): Partial<Model> {
  const endpoint =
    item.api_endpoint ??
    (item.provider === 'openai'
      ? item.type === 'image'
        ? 'https://api.openai.com/v1/images/generations'
        : item.type === 'video'
          ? 'https://api.openai.com/v1/videos'
          : item.type === 'audio'
            ? 'https://api.openai.com/v1/audio/speech'
            : 'https://api.openai.com/v1/responses'
      : item.provider === 'anthropic'
        ? 'https://api.anthropic.com/v1/messages'
        : item.provider === 'deepseek'
          ? 'https://api.deepseek.com/v1/chat/completions'
          : item.provider === 'dashscope'
            ? item.type === 'audio'
              ? 'https://dashscope.aliyuncs.com/api/v1/services/aigc/audio/speech/synthesis'
              : 'https://dashscope.aliyuncs.com/compatible-mode/v1'
            : item.provider === 'elevenlabs'
              ? 'https://api.elevenlabs.io/v1/text-to-speech'
              : item.provider === 'kling'
                ? 'https://api.klingai.com'
                : '')

  const integrationText =
    item.integration_status === 'native'
      ? '当前代码已存在原生调用路径。'
      : item.integration_status === 'config_only'
        ? '当前可入库展示，但下游服务尚未按 model_key 全链路消费。'
        : '当前仅做官方目录展示，若要实际调用还需新增适配器。'

  return {
    name: item.name,
    model_key: item.model_key,
    type: item.type,
    provider: item.provider,
    speed_rating: item.speed_rating,
    capability_tags: item.capability_tags,
    supports_consistency: item.supports_consistency ?? false,
    consistency_method: item.consistency_method ?? 'none',
    video_mode: item.video_mode,
    max_resolution: item.max_resolution,
    supported_ratios: item.supported_ratios ?? [],
    is_active: item.integration_status !== 'catalog_only',
    is_default: item.catalog_status === 'default' || item.catalog_status === 'recommended',
    api_endpoint: endpoint,
    context_window: item.context_window,
    input_price: item.input_price ?? 0,
    output_price: item.output_price ?? 0,
    cost_per_unit: item.cost_per_unit ?? 0,
    unit: item.unit ?? (item.type === 'video' ? 'second' : item.type === 'image' ? 'image' : '1M tokens'),
    priority: item.priority ?? defaultPriority(item.integration_status, item.catalog_status),
    description: `${item.description} 官方目录来源：${item.source_label}。接入结论：${integrationText}`,
    config: {
      official_catalog: true,
      catalog_status: item.catalog_status,
      integration_status: item.integration_status,
      source_url: item.source_url,
      source_label: item.source_label,
      runtime_alias: item.runtime_alias ?? null,
    },
  }
}

export const OFFICIAL_MODEL_CATALOG: OfficialModelCatalogItem[] = [
  {
    name: 'GPT-5.4',
    model_key: 'gpt-5.4',
    type: 'llm',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'default',
    integration_status: 'config_only',
    speed_rating: 'quality',
    capability_tags: ['text-generation', 'reasoning', 'vision', 'function-calling'],
    description: 'OpenAI 当前主推旗舰文本模型。',
    source_url: OPENAI_MODELS_URL,
    source_label: 'OpenAI Models',
    context_window: 1050000,
    input_price: 2.5,
    output_price: 15,
  },
  {
    name: 'GPT-5.4 Pro',
    model_key: 'gpt-5.4-pro',
    type: 'llm',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'latest',
    integration_status: 'config_only',
    speed_rating: 'quality',
    capability_tags: ['text-generation', 'reasoning', 'vision'],
    description: 'OpenAI GPT-5.4 的高精度版本。',
    source_url: OPENAI_ALL_MODELS_URL,
    source_label: 'OpenAI All Models',
  },
  {
    name: 'GPT-5.4 Mini',
    model_key: 'gpt-5.4-mini',
    type: 'llm',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'latest',
    integration_status: 'config_only',
    speed_rating: 'fast',
    capability_tags: ['text-generation', 'reasoning', 'vision', 'function-calling'],
    description: 'OpenAI 当前主推高性价比 mini 模型。',
    source_url: OPENAI_MODELS_URL,
    source_label: 'OpenAI Models',
    context_window: 400000,
    input_price: 0.75,
    output_price: 4.5,
  },
  {
    name: 'GPT-5.4 Nano',
    model_key: 'gpt-5.4-nano',
    type: 'llm',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'latest',
    integration_status: 'config_only',
    speed_rating: 'fast',
    capability_tags: ['text-generation', 'classification', 'extraction'],
    description: 'OpenAI 当前 GPT-5.4 系列最低成本模型。',
    source_url: OPENAI_MODELS_URL,
    source_label: 'OpenAI Models',
    context_window: 400000,
    input_price: 0.2,
    output_price: 1.25,
  },
  {
    name: 'GPT-5 Mini',
    model_key: 'gpt-5-mini',
    type: 'llm',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'latest',
    integration_status: 'config_only',
    speed_rating: 'fast',
    capability_tags: ['text-generation', 'reasoning'],
    description: 'OpenAI 低延迟 GPT-5 变体。',
    source_url: OPENAI_ALL_MODELS_URL,
    source_label: 'OpenAI All Models',
  },
  {
    name: 'GPT-5 Nano',
    model_key: 'gpt-5-nano',
    type: 'llm',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'latest',
    integration_status: 'config_only',
    speed_rating: 'fast',
    capability_tags: ['text-generation', 'classification'],
    description: 'OpenAI GPT-5 低成本版本。',
    source_url: OPENAI_ALL_MODELS_URL,
    source_label: 'OpenAI All Models',
  },
  {
    name: 'GPT-5',
    model_key: 'gpt-5',
    type: 'llm',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'legacy',
    integration_status: 'config_only',
    speed_rating: 'balanced',
    capability_tags: ['text-generation', 'reasoning', 'vision'],
    description: 'OpenAI 上一代推理旗舰。',
    source_url: OPENAI_ALL_MODELS_URL,
    source_label: 'OpenAI All Models',
  },
  {
    name: 'GPT-4.1',
    model_key: 'gpt-4.1',
    type: 'llm',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'legacy',
    integration_status: 'config_only',
    speed_rating: 'balanced',
    capability_tags: ['text-generation', 'vision', 'function-calling'],
    description: 'OpenAI 当前仍展示的非推理高性能模型。',
    source_url: OPENAI_ALL_MODELS_URL,
    source_label: 'OpenAI All Models',
  },
  {
    name: 'GPT-5-Codex',
    model_key: 'gpt-5-codex',
    type: 'llm',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['coding', 'agentic'],
    description: 'OpenAI 当前 Codex 优化模型。',
    source_url: OPENAI_ALL_MODELS_URL,
    source_label: 'OpenAI All Models',
  },
  {
    name: 'GPT-5.3-Codex',
    model_key: 'gpt-5.3-codex',
    type: 'llm',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'legacy',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['coding', 'agentic'],
    description: 'OpenAI 仍在目录中展示的 Codex 系列模型。',
    source_url: OPENAI_ALL_MODELS_URL,
    source_label: 'OpenAI All Models',
  },
  {
    name: 'GPT-5.2-Codex',
    model_key: 'gpt-5.2-codex',
    type: 'llm',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'legacy',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['coding', 'agentic'],
    description: 'OpenAI 仍在目录中展示的 GPT-5.2 Codex。',
    source_url: OPENAI_ALL_MODELS_URL,
    source_label: 'OpenAI All Models',
  },
  {
    name: 'GPT-5.1-Codex',
    model_key: 'gpt-5.1-codex',
    type: 'llm',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'legacy',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['coding', 'agentic'],
    description: 'OpenAI 历史 Codex 模型，当前仍在目录显示。',
    source_url: OPENAI_ALL_MODELS_URL,
    source_label: 'OpenAI All Models',
  },
  {
    name: 'GPT-5.1-Codex-Max',
    model_key: 'gpt-5.1-codex-max',
    type: 'llm',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'legacy',
    integration_status: 'catalog_only',
    speed_rating: 'quality',
    capability_tags: ['coding', 'agentic'],
    description: 'OpenAI 长时任务 Codex 变体。',
    source_url: OPENAI_ALL_MODELS_URL,
    source_label: 'OpenAI All Models',
  },
  {
    name: 'GPT-5.1-Codex-Mini',
    model_key: 'gpt-5.1-codex-mini',
    type: 'llm',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'legacy',
    integration_status: 'catalog_only',
    speed_rating: 'fast',
    capability_tags: ['coding', 'agentic'],
    description: 'OpenAI 低成本 Codex 变体。',
    source_url: OPENAI_ALL_MODELS_URL,
    source_label: 'OpenAI All Models',
  },
  {
    name: 'o3-deep-research',
    model_key: 'o3-deep-research',
    type: 'llm',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'quality',
    capability_tags: ['reasoning', 'deep-research', 'tool-use'],
    description: 'OpenAI 深度研究模型。',
    source_url: 'https://developers.openai.com/api/docs/models/o3-deep-research',
    source_label: 'OpenAI o3-deep-research',
    context_window: 200000,
    input_price: 10,
    output_price: 40,
  },
  {
    name: 'o4-mini-deep-research',
    model_key: 'o4-mini-deep-research',
    type: 'llm',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['reasoning', 'deep-research', 'tool-use'],
    description: 'OpenAI 更低成本的 deep research 模型。',
    source_url: OPENAI_ALL_MODELS_URL,
    source_label: 'OpenAI All Models',
  },
  {
    name: 'gpt-oss-120b',
    model_key: 'gpt-oss-120b',
    type: 'llm',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['open-weight', 'self-hosted'],
    description: 'OpenAI 当前开源权重最大模型。',
    source_url: OPENAI_ALL_MODELS_URL,
    source_label: 'OpenAI All Models',
  },
  {
    name: 'gpt-oss-20b',
    model_key: 'gpt-oss-20b',
    type: 'llm',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'fast',
    capability_tags: ['open-weight', 'self-hosted'],
    description: 'OpenAI 低延迟开源权重模型。',
    source_url: OPENAI_ALL_MODELS_URL,
    source_label: 'OpenAI All Models',
  },
  {
    name: 'GPT Image 1.5',
    model_key: 'gpt-image-1.5',
    type: 'image',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'default',
    integration_status: 'native',
    speed_rating: 'balanced',
    capability_tags: ['text-to-image', 'image-edit'],
    description: 'OpenAI 当前图像生成主模型。',
    source_url: OPENAI_MODELS_URL,
    source_label: 'OpenAI Models',
    max_resolution: '官方支持多尺寸',
    runtime_alias: 'dalle',
  },
  {
    name: 'GPT Image 1 Mini',
    model_key: 'gpt-image-1-mini',
    type: 'image',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'fast',
    capability_tags: ['text-to-image'],
    description: 'OpenAI 低成本图像生成模型。',
    source_url: OPENAI_MODELS_URL,
    source_label: 'OpenAI Models',
  },
  {
    name: 'Sora 2',
    model_key: 'sora-2',
    type: 'video',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'default',
    integration_status: 'native',
    speed_rating: 'quality',
    capability_tags: ['text-to-video', 'image-to-video', 'synced-audio'],
    description: 'OpenAI 当前视频主模型，支持同步音频。',
    source_url: OPENAI_SORA_URL,
    source_label: 'OpenAI Sora 2',
    cost_per_unit: 0.1,
    unit: 'second',
    video_mode: 'api_generation',
    max_resolution: '1280x720 / 720x1280',
    supported_ratios: ['16:9', '9:16'],
    runtime_alias: 'sora2',
  },
  {
    name: 'Sora 2 Pro',
    model_key: 'sora-2-pro',
    type: 'video',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'quality',
    capability_tags: ['text-to-video', 'image-to-video', 'synced-audio'],
    description: 'OpenAI 更高质量视频模型。',
    source_url: OPENAI_MODELS_URL,
    source_label: 'OpenAI Models',
    cost_per_unit: 0.3,
    unit: 'second',
    video_mode: 'api_generation',
  },
  {
    name: 'ComfyUI Local Video',
    model_key: 'comfyui-local-video',
    type: 'video',
    provider: 'custom',
    provider_label: 'ComfyUI',
    catalog_status: 'recommended',
    integration_status: 'native',
    speed_rating: 'balanced',
    capability_tags: ['image-to-video'],
    description: '本地 ComfyUI 图生视频工作流，适合接自建 Wan / AnimateDiff / 其他本地视频节点。',
    source_url: COMFYUI_URL,
    source_label: 'ComfyUI',
    video_mode: 'api_generation',
    runtime_alias: 'comfyui-video',
  },
  {
    name: 'gpt-realtime-1.5',
    model_key: 'gpt-realtime-1.5',
    type: 'audio',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'default',
    integration_status: 'catalog_only',
    speed_rating: 'fast',
    capability_tags: ['realtime', 'speech-to-speech'],
    description: 'OpenAI 当前语音对话主模型。',
    source_url: OPENAI_MODELS_URL,
    source_label: 'OpenAI Models',
  },
  {
    name: 'gpt-realtime-mini',
    model_key: 'gpt-realtime-mini',
    type: 'audio',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'fast',
    capability_tags: ['realtime', 'speech-to-speech'],
    description: 'OpenAI 低成本实时语音模型。',
    source_url: OPENAI_MODELS_URL,
    source_label: 'OpenAI Models',
  },
  {
    name: 'GPT-4o Mini TTS',
    model_key: 'gpt-4o-mini-tts',
    type: 'audio',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['text-to-speech'],
    description: 'OpenAI 文本转语音模型。',
    source_url: OPENAI_TTS_URL,
    source_label: 'OpenAI TTS',
  },
  {
    name: 'GPT-4o Transcribe',
    model_key: 'gpt-4o-transcribe',
    type: 'audio',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['speech-to-text'],
    description: 'OpenAI 语音转文字模型。',
    source_url: OPENAI_MODELS_URL,
    source_label: 'OpenAI Models',
  },
  {
    name: 'GPT-4o Mini Transcribe',
    model_key: 'gpt-4o-mini-transcribe',
    type: 'audio',
    provider: 'openai',
    provider_label: 'OpenAI',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'fast',
    capability_tags: ['speech-to-text'],
    description: 'OpenAI 低成本语音转文字模型。',
    source_url: OPENAI_MODELS_URL,
    source_label: 'OpenAI Models',
  },
  {
    name: 'Claude Opus 4.6',
    model_key: 'claude-opus-4-6',
    type: 'llm',
    provider: 'anthropic',
    provider_label: 'Anthropic',
    catalog_status: 'default',
    integration_status: 'config_only',
    speed_rating: 'quality',
    capability_tags: ['text-generation', 'vision', 'reasoning'],
    description: 'Anthropic 当前推荐的最高能力模型。',
    source_url: ANTHROPIC_MODELS_URL,
    source_label: 'Anthropic Models Overview',
    context_window: 1000000,
    input_price: 5,
    output_price: 25,
  },
  {
    name: 'Claude Sonnet 4.6',
    model_key: 'claude-sonnet-4-6',
    type: 'llm',
    provider: 'anthropic',
    provider_label: 'Anthropic',
    catalog_status: 'latest',
    integration_status: 'config_only',
    speed_rating: 'balanced',
    capability_tags: ['text-generation', 'vision', 'reasoning'],
    description: 'Anthropic 当前主流高性能模型。',
    source_url: ANTHROPIC_MODELS_URL,
    source_label: 'Anthropic Models Overview',
    context_window: 1000000,
    input_price: 3,
    output_price: 15,
  },
  {
    name: 'Claude Haiku 4.5',
    model_key: 'claude-haiku-4-5',
    type: 'llm',
    provider: 'anthropic',
    provider_label: 'Anthropic',
    catalog_status: 'latest',
    integration_status: 'config_only',
    speed_rating: 'fast',
    capability_tags: ['text-generation', 'vision'],
    description: 'Anthropic 当前最快 Claude 模型。',
    source_url: ANTHROPIC_MODELS_URL,
    source_label: 'Anthropic Models Overview',
    context_window: 200000,
    input_price: 1,
    output_price: 5,
  },
  {
    name: 'Claude Opus 4',
    model_key: 'claude-opus-4-20250514',
    type: 'llm',
    provider: 'anthropic',
    provider_label: 'Anthropic',
    catalog_status: 'legacy',
    integration_status: 'config_only',
    speed_rating: 'quality',
    capability_tags: ['text-generation', 'vision', 'reasoning'],
    description: 'Anthropic 仍在概览中展示的旧版本快照。',
    source_url: 'https://docs.anthropic.com/en/docs/models-overview',
    source_label: 'Anthropic Legacy Overview',
  },
  {
    name: 'Claude Sonnet 4',
    model_key: 'claude-sonnet-4-20250514',
    type: 'llm',
    provider: 'anthropic',
    provider_label: 'Anthropic',
    catalog_status: 'legacy',
    integration_status: 'config_only',
    speed_rating: 'balanced',
    capability_tags: ['text-generation', 'vision', 'reasoning'],
    description: 'Anthropic 仍在概览中展示的 Sonnet 4 快照。',
    source_url: 'https://docs.anthropic.com/en/docs/models-overview',
    source_label: 'Anthropic Legacy Overview',
  },
  {
    name: 'Claude Sonnet 3.7',
    model_key: 'claude-3-7-sonnet-latest',
    type: 'llm',
    provider: 'anthropic',
    provider_label: 'Anthropic',
    catalog_status: 'legacy',
    integration_status: 'config_only',
    speed_rating: 'balanced',
    capability_tags: ['text-generation', 'vision', 'reasoning'],
    description: 'Anthropic 仍在旧版概览列出的 Claude 3.7 Sonnet 别名。',
    source_url: 'https://docs.anthropic.com/en/docs/models-overview',
    source_label: 'Anthropic Legacy Overview',
  },
  {
    name: 'Claude Sonnet 3.7 Snapshot',
    model_key: 'claude-3-7-sonnet-20250219',
    type: 'llm',
    provider: 'anthropic',
    provider_label: 'Anthropic',
    catalog_status: 'snapshot',
    integration_status: 'config_only',
    speed_rating: 'balanced',
    capability_tags: ['text-generation', 'vision', 'reasoning'],
    description: 'Anthropic Claude 3.7 Sonnet 快照版。',
    source_url: 'https://docs.anthropic.com/en/docs/models-overview',
    source_label: 'Anthropic Legacy Overview',
  },
  {
    name: 'Claude Haiku 3.5',
    model_key: 'claude-3-5-haiku-latest',
    type: 'llm',
    provider: 'anthropic',
    provider_label: 'Anthropic',
    catalog_status: 'legacy',
    integration_status: 'config_only',
    speed_rating: 'fast',
    capability_tags: ['text-generation', 'vision'],
    description: 'Anthropic 仍在旧版概览列出的 Haiku 3.5 别名。',
    source_url: 'https://docs.anthropic.com/en/docs/models-overview',
    source_label: 'Anthropic Legacy Overview',
  },
  {
    name: 'Claude Haiku 3.5 Snapshot',
    model_key: 'claude-3-5-haiku-20241022',
    type: 'llm',
    provider: 'anthropic',
    provider_label: 'Anthropic',
    catalog_status: 'snapshot',
    integration_status: 'config_only',
    speed_rating: 'fast',
    capability_tags: ['text-generation', 'vision'],
    description: 'Anthropic Claude Haiku 3.5 快照版。',
    source_url: 'https://docs.anthropic.com/en/docs/models-overview',
    source_label: 'Anthropic Legacy Overview',
  },
  {
    name: 'Claude Haiku 3',
    model_key: 'claude-3-haiku-20240307',
    type: 'llm',
    provider: 'anthropic',
    provider_label: 'Anthropic',
    catalog_status: 'legacy',
    integration_status: 'config_only',
    speed_rating: 'fast',
    capability_tags: ['text-generation', 'vision'],
    description: 'Anthropic 旧版 Haiku 3。',
    source_url: 'https://docs.anthropic.com/en/docs/models-overview',
    source_label: 'Anthropic Legacy Overview',
  },
  {
    name: 'DeepSeek Chat',
    model_key: 'deepseek-chat',
    type: 'llm',
    provider: 'deepseek',
    provider_label: 'DeepSeek',
    catalog_status: 'default',
    integration_status: 'config_only',
    speed_rating: 'fast',
    capability_tags: ['text-generation', 'function-calling'],
    description: 'DeepSeek 非思考模式主模型。',
    source_url: DEEPSEEK_PRICING_URL,
    source_label: 'DeepSeek Models & Pricing',
    context_window: 128000,
    input_price: 0.28,
    output_price: 0.42,
  },
  {
    name: 'DeepSeek Reasoner',
    model_key: 'deepseek-reasoner',
    type: 'llm',
    provider: 'deepseek',
    provider_label: 'DeepSeek',
    catalog_status: 'latest',
    integration_status: 'config_only',
    speed_rating: 'balanced',
    capability_tags: ['reasoning', 'json-output'],
    description: 'DeepSeek 推理模型。',
    source_url: DEEPSEEK_MODELS_URL,
    source_label: 'DeepSeek List Models',
    context_window: 128000,
  },
  {
    name: 'Qwen3 Max',
    model_key: 'qwen3-max',
    type: 'llm',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'latest',
    integration_status: 'config_only',
    speed_rating: 'quality',
    capability_tags: ['text-generation', 'reasoning'],
    description: '阿里云百炼当前商业旗舰千问模型。',
    source_url: DASHSCOPE_TEXT_URL,
    source_label: 'DashScope OpenAI Compatible',
  },
  {
    name: 'Qwen3 Max Preview',
    model_key: 'qwen3-max-preview',
    type: 'llm',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'preview',
    integration_status: 'config_only',
    speed_rating: 'quality',
    capability_tags: ['text-generation', 'reasoning'],
    description: '阿里云百炼 Qwen3 Max 预览版。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
  },
  {
    name: 'Qwen Max',
    model_key: 'qwen-max',
    type: 'llm',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'stable',
    integration_status: 'config_only',
    speed_rating: 'quality',
    capability_tags: ['text-generation'],
    description: '阿里云百炼 qwen-max 稳定别名。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
  },
  {
    name: 'Qwen Max Latest',
    model_key: 'qwen-max-latest',
    type: 'llm',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'latest',
    integration_status: 'config_only',
    speed_rating: 'quality',
    capability_tags: ['text-generation'],
    description: '阿里云百炼 qwen-max 最新别名。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
  },
  {
    name: 'Qwen Max Snapshot',
    model_key: 'qwen-max-2025-01-25',
    type: 'llm',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'snapshot',
    integration_status: 'config_only',
    speed_rating: 'quality',
    capability_tags: ['text-generation'],
    description: '阿里云百炼 qwen-max 当前文档中显式列出的快照。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
  },
  {
    name: 'Qwen Plus',
    model_key: 'qwen-plus',
    type: 'llm',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'stable',
    integration_status: 'config_only',
    speed_rating: 'balanced',
    capability_tags: ['text-generation', 'reasoning'],
    description: '阿里云百炼主力通用模型。',
    source_url: DASHSCOPE_TEXT_URL,
    source_label: 'DashScope OpenAI Compatible',
  },
  {
    name: 'Qwen Plus Latest',
    model_key: 'qwen-plus-latest',
    type: 'llm',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'latest',
    integration_status: 'config_only',
    speed_rating: 'balanced',
    capability_tags: ['text-generation', 'reasoning'],
    description: '阿里云百炼 qwen-plus 最新别名。',
    source_url: DASHSCOPE_TEXT_URL,
    source_label: 'DashScope OpenAI Compatible',
  },
  {
    name: 'Qwen3.5 Plus',
    model_key: 'qwen3.5-plus',
    type: 'llm',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'latest',
    integration_status: 'config_only',
    speed_rating: 'balanced',
    capability_tags: ['text-generation', 'reasoning'],
    description: '阿里云百炼 Responses 兼容接口当前显式支持的模型。',
    source_url: 'https://help.aliyun.com/zh/model-studio/compatibility-with-openai-responses-api',
    source_label: 'DashScope Responses Compatible',
  },
  {
    name: 'Qwen Flash',
    model_key: 'qwen-flash',
    type: 'llm',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'latest',
    integration_status: 'config_only',
    speed_rating: 'fast',
    capability_tags: ['text-generation', 'reasoning'],
    description: '阿里云百炼当前更低延迟文本模型。',
    source_url: DASHSCOPE_TEXT_URL,
    source_label: 'DashScope OpenAI Compatible',
  },
  {
    name: 'Qwen Turbo',
    model_key: 'qwen-turbo',
    type: 'llm',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'stable',
    integration_status: 'config_only',
    speed_rating: 'fast',
    capability_tags: ['text-generation', 'reasoning'],
    description: '阿里云百炼 qwen-turbo 稳定别名。',
    source_url: DASHSCOPE_TEXT_URL,
    source_label: 'DashScope OpenAI Compatible',
  },
  {
    name: 'Qwen Turbo Latest',
    model_key: 'qwen-turbo-latest',
    type: 'llm',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'latest',
    integration_status: 'config_only',
    speed_rating: 'fast',
    capability_tags: ['text-generation', 'reasoning'],
    description: '阿里云百炼 qwen-turbo 最新别名。',
    source_url: DASHSCOPE_TEXT_URL,
    source_label: 'DashScope OpenAI Compatible',
  },
  {
    name: 'Qwen3 Coder Plus',
    model_key: 'qwen3-coder-plus',
    type: 'llm',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['coding'],
    description: '阿里云百炼当前 Coder 系列模型。',
    source_url: DASHSCOPE_TEXT_URL,
    source_label: 'DashScope OpenAI Compatible',
  },
  {
    name: 'Qwen3 Coder Flash',
    model_key: 'qwen3-coder-flash',
    type: 'llm',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'fast',
    capability_tags: ['coding'],
    description: '阿里云百炼当前低延迟 Coder 模型。',
    source_url: DASHSCOPE_TEXT_URL,
    source_label: 'DashScope OpenAI Compatible',
  },
  {
    name: 'Qwen-VL Max',
    model_key: 'qwen-vl-max',
    type: 'image',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'stable',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['vision-understanding'],
    description: '阿里云百炼视觉理解模型，当前项目未接入视觉问答链路。',
    source_url: DASHSCOPE_VISION_URL,
    source_label: 'DashScope Vision Compatible',
    context_window: 131072,
  },
  {
    name: 'Qwen-VL Max Latest',
    model_key: 'qwen-vl-max-latest',
    type: 'image',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['vision-understanding'],
    description: '阿里云百炼视觉模型最新别名。',
    source_url: DASHSCOPE_VISION_URL,
    source_label: 'DashScope Vision Compatible',
    context_window: 131072,
  },
  {
    name: 'Qwen-VL Plus',
    model_key: 'qwen-vl-plus',
    type: 'image',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'stable',
    integration_status: 'catalog_only',
    speed_rating: 'fast',
    capability_tags: ['vision-understanding'],
    description: '阿里云百炼视觉理解模型 plus 版本。',
    source_url: DASHSCOPE_VISION_URL,
    source_label: 'DashScope Vision Compatible',
  },
  {
    name: 'Wan 2.6 T2I',
    model_key: 'wan2.6-t2i',
    type: 'image',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'recommended',
    integration_status: 'catalog_only',
    speed_rating: 'quality',
    capability_tags: ['text-to-image'],
    description: '阿里云百炼当前推荐的万相文生图模型。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
    cost_per_unit: 0.2,
    unit: 'image',
  },
  {
    name: 'Wan 2.5 T2I Preview',
    model_key: 'wan2.5-t2i-preview',
    type: 'image',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'preview',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['text-to-image'],
    description: '阿里云百炼万相 2.5 预览版文生图。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
    cost_per_unit: 0.2,
    unit: 'image',
  },
  {
    name: 'Wan 2.2 T2I Plus',
    model_key: 'wan2.2-t2i-plus',
    type: 'image',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['text-to-image'],
    description: '阿里云百炼万相 2.2 专业版文生图。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
    cost_per_unit: 0.2,
    unit: 'image',
  },
  {
    name: 'Wan 2.2 T2I Flash',
    model_key: 'wan2.2-t2i-flash',
    type: 'image',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'fast',
    capability_tags: ['text-to-image'],
    description: '阿里云百炼万相 2.2 极速版文生图。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
    cost_per_unit: 0.14,
    unit: 'image',
  },
  {
    name: 'WanX 2.1 T2I Plus',
    model_key: 'wanx2.1-t2i-plus',
    type: 'image',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'legacy',
    integration_status: 'native',
    speed_rating: 'balanced',
    capability_tags: ['text-to-image'],
    description: '当前项目 Tongyi 图片生成器最接近的官方型号。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
    cost_per_unit: 0.2,
    unit: 'image',
    runtime_alias: 'tongyi',
  },
  {
    name: 'WanX 2.1 T2I Turbo',
    model_key: 'wanx2.1-t2i-turbo',
    type: 'image',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'legacy',
    integration_status: 'catalog_only',
    speed_rating: 'fast',
    capability_tags: ['text-to-image'],
    description: '阿里云百炼旧版万相极速文生图。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
  },
  {
    name: 'Wan 2.6 T2V',
    model_key: 'wan2.6-t2v',
    type: 'video',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'recommended',
    integration_status: 'catalog_only',
    speed_rating: 'quality',
    capability_tags: ['text-to-video', 'audio'],
    description: '阿里云百炼当前推荐万相文生视频模型。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
    cost_per_unit: 0.6,
    unit: 'second',
    video_mode: 'api_generation',
  },
  {
    name: 'Wan 2.5 T2V Preview',
    model_key: 'wan2.5-t2v-preview',
    type: 'video',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'preview',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['text-to-video', 'audio'],
    description: '阿里云百炼万相 2.5 预览文生视频。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
    video_mode: 'api_generation',
  },
  {
    name: 'Wan 2.2 T2V Plus',
    model_key: 'wan2.2-t2v-plus',
    type: 'video',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['text-to-video'],
    description: '阿里云百炼万相 2.2 专业版文生视频。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
    video_mode: 'api_generation',
  },
  {
    name: 'WanX 2.1 T2V Turbo',
    model_key: 'wanx2.1-t2v-turbo',
    type: 'video',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'legacy',
    integration_status: 'catalog_only',
    speed_rating: 'fast',
    capability_tags: ['text-to-video'],
    description: '阿里云百炼万相 2.1 极速文生视频。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
    video_mode: 'api_generation',
  },
  {
    name: 'WanX 2.1 T2V Plus',
    model_key: 'wanx2.1-t2v-plus',
    type: 'video',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'legacy',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['text-to-video'],
    description: '阿里云百炼万相 2.1 专业版文生视频。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
    video_mode: 'api_generation',
  },
  {
    name: 'Wan 2.6 I2V Flash',
    model_key: 'wan2.6-i2v-flash',
    type: 'video',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'recommended',
    integration_status: 'catalog_only',
    speed_rating: 'fast',
    capability_tags: ['image-to-video', 'audio'],
    description: '阿里云百炼当前推荐万相图生视频极速版。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
    video_mode: 'api_generation',
  },
  {
    name: 'Wan 2.6 I2V',
    model_key: 'wan2.6-i2v',
    type: 'video',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'recommended',
    integration_status: 'catalog_only',
    speed_rating: 'quality',
    capability_tags: ['image-to-video', 'audio'],
    description: '阿里云百炼当前推荐万相图生视频专业版。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
    video_mode: 'api_generation',
  },
  {
    name: 'Wan 2.5 I2V Preview',
    model_key: 'wan2.5-i2v-preview',
    type: 'video',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'preview',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['image-to-video', 'audio'],
    description: '阿里云百炼万相 2.5 预览图生视频。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
    video_mode: 'api_generation',
  },
  {
    name: 'Wan 2.2 I2V Flash',
    model_key: 'wan2.2-i2v-flash',
    type: 'video',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'fast',
    capability_tags: ['image-to-video'],
    description: '阿里云百炼万相 2.2 极速图生视频。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
    video_mode: 'api_generation',
  },
  {
    name: 'Wan 2.2 I2V Plus',
    model_key: 'wan2.2-i2v-plus',
    type: 'video',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['image-to-video'],
    description: '阿里云百炼万相 2.2 专业图生视频。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
    video_mode: 'api_generation',
  },
  {
    name: 'WanX 2.1 I2V Turbo',
    model_key: 'wanx2.1-i2v-turbo',
    type: 'video',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'legacy',
    integration_status: 'native',
    speed_rating: 'fast',
    capability_tags: ['image-to-video'],
    description: '当前项目 wan 视频生成器最接近的官方型号。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
    video_mode: 'api_generation',
    runtime_alias: 'wan',
  },
  {
    name: 'WanX 2.1 I2V Plus',
    model_key: 'wanx2.1-i2v-plus',
    type: 'video',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'legacy',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['image-to-video'],
    description: '阿里云百炼万相 2.1 专业图生视频。',
    source_url: DASHSCOPE_MODELS_URL,
    source_label: 'DashScope Models',
    video_mode: 'api_generation',
  },
  {
    name: 'CosyVoice v3.5 Plus',
    model_key: 'cosyvoice-v3.5-plus',
    type: 'audio',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'quality',
    capability_tags: ['text-to-speech', 'dialect'],
    description: '阿里云百炼当前高规格 TTS 模型。',
    source_url: DASHSCOPE_TTS_URL,
    source_label: 'DashScope TTS',
  },
  {
    name: 'CosyVoice v3 Plus',
    model_key: 'cosyvoice-v3-plus',
    type: 'audio',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'balanced',
    capability_tags: ['text-to-speech', 'ssml'],
    description: '阿里云百炼 TTS 模型，支持更丰富播报场景。',
    source_url: DASHSCOPE_TTS_URL,
    source_label: 'DashScope TTS',
  },
  {
    name: 'CosyVoice v3 Flash',
    model_key: 'cosyvoice-v3-flash',
    type: 'audio',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'fast',
    capability_tags: ['text-to-speech', 'ssml'],
    description: '阿里云百炼低延迟 TTS 模型。',
    source_url: DASHSCOPE_TTS_URL,
    source_label: 'DashScope TTS',
  },
  {
    name: 'CosyVoice v2',
    model_key: 'cosyvoice-v2',
    type: 'audio',
    provider: 'dashscope',
    provider_label: 'DashScope',
    catalog_status: 'legacy',
    integration_status: 'native',
    speed_rating: 'balanced',
    capability_tags: ['text-to-speech'],
    description: '当前项目已有种子配置的阿里云 TTS 模型。',
    source_url: DASHSCOPE_TTS_URL,
    source_label: 'DashScope TTS',
  },
  {
    name: 'Eleven v3',
    model_key: 'eleven_v3',
    type: 'audio',
    provider: 'elevenlabs',
    provider_label: 'ElevenLabs',
    catalog_status: 'default',
    integration_status: 'catalog_only',
    speed_rating: 'quality',
    capability_tags: ['text-to-speech', 'multi-speaker'],
    description: 'ElevenLabs 当前主推情感表达最强 TTS 模型。',
    source_url: ELEVENLABS_MODELS_URL,
    source_label: 'ElevenLabs Models',
  },
  {
    name: 'Eleven Multilingual v2',
    model_key: 'eleven_multilingual_v2',
    type: 'audio',
    provider: 'elevenlabs',
    provider_label: 'ElevenLabs',
    catalog_status: 'stable',
    integration_status: 'native',
    speed_rating: 'balanced',
    capability_tags: ['text-to-speech', 'multilingual'],
    description: '当前项目种子模型最接近 ElevenLabs 官方稳定语音模型。',
    source_url: ELEVENLABS_API_MODELS_URL,
    source_label: 'ElevenLabs Model API',
    runtime_alias: 'eleven_multilingual_v2',
  },
  {
    name: 'Eleven Flash v2.5',
    model_key: 'eleven_flash_v2_5',
    type: 'audio',
    provider: 'elevenlabs',
    provider_label: 'ElevenLabs',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'fast',
    capability_tags: ['text-to-speech', 'low-latency'],
    description: 'ElevenLabs 当前低延迟 TTS 模型。',
    source_url: ELEVENLABS_MODELS_URL,
    source_label: 'ElevenLabs Models',
  },
  {
    name: 'Eleven Turbo v2.5',
    model_key: 'eleven_turbo_v2_5',
    type: 'audio',
    provider: 'elevenlabs',
    provider_label: 'ElevenLabs',
    catalog_status: 'latest',
    integration_status: 'catalog_only',
    speed_rating: 'fast',
    capability_tags: ['text-to-speech'],
    description: 'ElevenLabs 质量与速度平衡的 TTS 模型。',
    source_url: ELEVENLABS_MODELS_URL,
    source_label: 'ElevenLabs Models',
  },
  {
    name: 'Kling 2.1',
    model_key: 'kling-2.1',
    type: 'video',
    provider: 'kling',
    provider_label: 'Kling AI',
    catalog_status: 'default',
    integration_status: 'catalog_only',
    speed_rating: 'quality',
    capability_tags: ['text-to-video', 'image-to-video'],
    description: 'Kling 官方当前公开主推版本。',
    source_url: KLING_MODELS_URL,
    source_label: 'Kling AI',
    video_mode: 'api_generation',
  },
  {
    name: 'Kling 1.6',
    model_key: 'kling-v1-6',
    type: 'video',
    provider: 'kling',
    provider_label: 'Kling AI',
    catalog_status: 'legacy',
    integration_status: 'native',
    speed_rating: 'balanced',
    capability_tags: ['text-to-video', 'image-to-video'],
    description: '当前项目后端硬编码接入的 Kling 版本。',
    source_url: KLING_MODELS_URL,
    source_label: 'Kling AI',
    video_mode: 'api_generation',
    runtime_alias: 'kling',
  },
]
