// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/model.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ─── Client ──────────────────────────────────────────────────────────────────

// ModelServiceClient is the client API for ModelService service.
type ModelServiceClient interface {
	RouteModel(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error)
	RecordUsage(ctx context.Context, in *RecordUsageRequest, opts ...grpc.CallOption) (*RecordUsageResponse, error)
	GetModelInfo(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*ModelInfo, error)
}

type modelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelServiceClient(cc grpc.ClientConnInterface) ModelServiceClient {
	return &modelServiceClient{cc}
}

func (c *modelServiceClient) RouteModel(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error) {
	out := new(RouteResponse)
	err := c.cc.Invoke(ctx, "/model.v1.ModelService/RouteModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) RecordUsage(ctx context.Context, in *RecordUsageRequest, opts ...grpc.CallOption) (*RecordUsageResponse, error) {
	out := new(RecordUsageResponse)
	err := c.cc.Invoke(ctx, "/model.v1.ModelService/RecordUsage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) GetModelInfo(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*ModelInfo, error) {
	out := new(ModelInfo)
	err := c.cc.Invoke(ctx, "/model.v1.ModelService/GetModelInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ─── Server ──────────────────────────────────────────────────────────────────

// ModelServiceServer is the server API for ModelService service.
// All implementations must embed UnimplementedModelServiceServer for forward compatibility.
type ModelServiceServer interface {
	RouteModel(context.Context, *RouteRequest) (*RouteResponse, error)
	RecordUsage(context.Context, *RecordUsageRequest) (*RecordUsageResponse, error)
	GetModelInfo(context.Context, *GetModelRequest) (*ModelInfo, error)
	mustEmbedUnimplementedModelServiceServer()
}

// UnimplementedModelServiceServer must be embedded to have forward compatible implementations.
type UnimplementedModelServiceServer struct{}

func (UnimplementedModelServiceServer) RouteModel(context.Context, *RouteRequest) (*RouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RouteModel not implemented")
}
func (UnimplementedModelServiceServer) RecordUsage(context.Context, *RecordUsageRequest) (*RecordUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordUsage not implemented")
}
func (UnimplementedModelServiceServer) GetModelInfo(context.Context, *GetModelRequest) (*ModelInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelInfo not implemented")
}
func (UnimplementedModelServiceServer) mustEmbedUnimplementedModelServiceServer() {}

// UnsafeModelServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeModelServiceServer interface {
	mustEmbedUnimplementedModelServiceServer()
}

// RegisterModelServiceServer registers an implementation with a gRPC server.
func RegisterModelServiceServer(s grpc.ServiceRegistrar, srv ModelServiceServer) {
	s.RegisterService(&ModelService_ServiceDesc, srv)
}

func _ModelService_RouteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).RouteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.v1.ModelService/RouteModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).RouteModel(ctx, req.(*RouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_RecordUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).RecordUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.v1.ModelService/RecordUsage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).RecordUsage(ctx, req.(*RecordUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_GetModelInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).GetModelInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.v1.ModelService/GetModelInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).GetModelInfo(ctx, req.(*GetModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelService_ServiceDesc is the grpc.ServiceDesc for ModelService service.
var ModelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "model.v1.ModelService",
	HandlerType: (*ModelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RouteModel",
			Handler:    _ModelService_RouteModel_Handler,
		},
		{
			MethodName: "RecordUsage",
			Handler:    _ModelService_RecordUsage_Handler,
		},
		{
			MethodName: "GetModelInfo",
			Handler:    _ModelService_GetModelInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/model.proto",
}
