import { normalizeVideoStylePreset } from '@/lib/video-style-config'
import { VIDEO_STYLE_PRESET_LABELS, VIDEO_MOTION_MODE_LABELS, VIDEO_RUNTIME_KEY_LABELS } from './create-config'

export type ProjectPresetTemplate = {
  key: string
  label: string
  desc: string
  tags: readonly string[]
  keywords: readonly string[]
  styleTags: readonly string[]
  videoStylePreset: string
  videoMotionMode: string
  storyboardAspectRatio: string
  storyboardResolution: string
  storyboardDuration: number
  consistencyStrength: number
  enableDubbing: boolean
  enableSubtitle: boolean
  videoMode: 'frame_animation' | 'api_generation'
  preferredVideoRuntimeKeys: readonly string[]
}

export const PROJECT_PRESET_TEMPLATES: ProjectPresetTemplate[] = ([
  {
    key: 'myth-guofeng',
    label: '神话国风',
    desc: '适合西游、仙侠、东方奇幻和宏大古典场景。',
    tags: ['国风', '神话', '史诗'],
    keywords: ['西游', '神话', '仙侠', '东方', '国风', '妖', '神', '佛', '天宫', '取经', '玄幻'],
    styleTags: ['古风', '水墨', '写实'],
    videoStylePreset: 'guofeng-myth',
    videoMotionMode: 'cinematic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1920x1080',
    storyboardDuration: 6,
    consistencyStrength: 85,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['wan', 'sora2'],
  },
  {
    key: 'urban-romance',
    label: '都市情感',
    desc: '适合都市夜景、人物关系和情绪戏。',
    tags: ['都市', '情感', '人物'],
    keywords: ['都市', '爱情', '恋爱', '情感', '夜景', '职场', '关系', '现代'],
    styleTags: ['写实', '极简'],
    videoStylePreset: 'urban-romance',
    videoMotionMode: 'gentle',
    storyboardAspectRatio: '9:16',
    storyboardResolution: '1080x1920',
    storyboardDuration: 5,
    consistencyStrength: 80,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['hubagi-voe3.1', 'wan'],
  },
  {
    key: 'suspense-investigation',
    label: '悬疑调查',
    desc: '适合压迫氛围、调查推进、反转叙事。',
    tags: ['悬疑', '惊悚', '暗调'],
    keywords: ['悬疑', '惊悚', '调查', '案件', '犯罪', '迷雾', '反转', '侦探'],
    styleTags: ['写实', '赛博朋克'],
    videoStylePreset: 'suspense-dark',
    videoMotionMode: 'cinematic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1280x720',
    storyboardDuration: 5,
    consistencyStrength: 78,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['sora2', 'wan'],
  },
  {
    key: 'documentary',
    label: '纪实纪录片',
    desc: '适合人物观察、采访跟拍和真实质感。',
    tags: ['纪录片', '真实', '自然'],
    keywords: ['纪录片', '纪实', '采访', '观察', '自然', '真实', '人物', '跟拍'],
    styleTags: ['写实', '极简'],
    videoStylePreset: 'documentary-natural',
    videoMotionMode: 'gentle',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1920x1080',
    storyboardDuration: 6,
    consistencyStrength: 70,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['hubagi-voe3.1', 'wan'],
  },
  {
    key: 'fashion-commercial',
    label: '时尚广告',
    desc: '适合品牌宣传、人物主视觉和高质感广告片。',
    tags: ['广告', '时尚', '人物'],
    keywords: ['广告', '品牌', '时尚', '宣传', '产品', '商业', '海报', '大片'],
    styleTags: ['写实', '3D渲染'],
    videoStylePreset: 'fashion-commercial',
    videoMotionMode: 'dynamic',
    storyboardAspectRatio: '9:16',
    storyboardResolution: '1080x1920',
    storyboardDuration: 4,
    consistencyStrength: 88,
    enableDubbing: false,
    enableSubtitle: false,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['hubagi-voe3.1', 'hubagi-TC-GV'],
  },
  {
    key: 'anime-action',
    label: '热血动漫',
    desc: '适合少年冒险、战斗、追逐和高能分镜。',
    tags: ['动漫', '动作', '热血'],
    keywords: ['动漫', '热血', '战斗', '冒险', '少年', '追逐', '动作', '校园'],
    styleTags: ['漫画', '动漫'],
    videoStylePreset: 'comic-dynamic',
    videoMotionMode: 'dynamic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1280x720',
    storyboardDuration: 5,
    consistencyStrength: 82,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['wan', 'hubagi-TC-GV'],
  },
  {
    key: 'explainer-comic',
    label: '解说漫',
    desc: '适合漫画风讲解视频、剧情盘点、角色故事梳理和旁白驱动内容。',
    tags: ['解说漫', '漫画风', '旁白'],
    keywords: ['解说漫', '漫画解说', '旁白', '盘点', '讲解', '剧情梳理', '角色解析', '世界观', '设定介绍', '条漫视频'],
    styleTags: ['漫画', '动漫', '条漫', '角色演出'],
    videoStylePreset: 'comic-dynamic',
    videoMotionMode: 'gentle',
    storyboardAspectRatio: '9:16',
    storyboardResolution: '1080x1920',
    storyboardDuration: 4,
    consistencyStrength: 84,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['wan', 'hubagi-TC-GV'],
  },
  {
    key: 'xianxia-fantasy',
    label: '仙侠玄幻',
    desc: '适合修仙成长、宗门争斗、秘境历练与东方奇幻。',
    tags: ['仙侠', '玄幻', '成长'],
    keywords: ['仙侠', '修仙', '宗门', '秘境', '灵气', '飞升', '法宝', '玄幻', '仙门', '道心'],
    styleTags: ['古风', '仙侠', '水墨', '史诗'],
    videoStylePreset: 'guofeng-myth',
    videoMotionMode: 'cinematic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1920x1080',
    storyboardDuration: 6,
    consistencyStrength: 86,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['wan', 'sora2'],
  },
  {
    key: 'wuxia-jianghu',
    label: '武侠江湖',
    desc: '适合门派恩怨、江湖追杀、侠义对决和古风打戏。',
    tags: ['武侠', '江湖', '动作'],
    keywords: ['武侠', '江湖', '门派', '侠客', '剑', '刀', '掌门', '追杀', '镖局', '恩怨'],
    styleTags: ['武侠', '古风', '写实', '水墨'],
    videoStylePreset: 'guofeng-myth',
    videoMotionMode: 'dynamic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1280x720',
    storyboardDuration: 5,
    consistencyStrength: 84,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['wan', 'hubagi-TC-GV'],
  },
  {
    key: 'palace-intrigue',
    label: '宫廷权谋',
    desc: '适合后宫博弈、朝堂斗争、隐忍反击和人物关系戏。',
    tags: ['宫廷', '权谋', '古装'],
    keywords: ['宫廷', '后宫', '权谋', '皇帝', '太后', '嫔妃', '朝堂', '争宠', '古装', '谋略'],
    styleTags: ['宫廷', '古风', '写实', '复古胶片'],
    videoStylePreset: 'realistic-drama',
    videoMotionMode: 'gentle',
    storyboardAspectRatio: '9:16',
    storyboardResolution: '1080x1920',
    storyboardDuration: 5,
    consistencyStrength: 83,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['hubagi-voe3.1', 'wan'],
  },
  {
    key: 'republic-spy',
    label: '民国谍战',
    desc: '适合潜伏、破译、追踪和旧时代紧张氛围。',
    tags: ['民国', '谍战', '悬疑'],
    keywords: ['民国', '谍战', '特工', '破译', '潜伏', '军统', '电台', '上海', '卧底', '暗线'],
    styleTags: ['民国', '悬疑', '复古胶片', '黑色电影'],
    videoStylePreset: 'vintage-film',
    videoMotionMode: 'cinematic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1280x720',
    storyboardDuration: 5,
    consistencyStrength: 81,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['sora2', 'wan'],
  },
  {
    key: 'campus-youth',
    label: '校园青春',
    desc: '适合成长、友情、暗恋、社团和轻松明亮的青春故事。',
    tags: ['校园', '青春', '成长'],
    keywords: ['校园', '青春', '高中', '大学', '社团', '毕业', '暗恋', '同学', '成长', '青春片'],
    styleTags: ['青春', '日系', '治愈', '写实'],
    videoStylePreset: 'warm-healing',
    videoMotionMode: 'gentle',
    storyboardAspectRatio: '9:16',
    storyboardResolution: '1080x1920',
    storyboardDuration: 4,
    consistencyStrength: 76,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['hubagi-voe3.1', 'wan'],
  },
  {
    key: 'sci-fi-apocalypse',
    label: '科幻末日',
    desc: '适合灾变求生、未来都市、废土冒险和高压节奏。',
    tags: ['科幻', '末日', '废土'],
    keywords: ['科幻', '末日', '废土', '灾变', '机甲', '未来', '病毒', '丧尸', '避难所', '求生'],
    styleTags: ['科幻', '末日废土', '赛博朋克', '史诗'],
    videoStylePreset: 'sci-fi-neon',
    videoMotionMode: 'dynamic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1920x1080',
    storyboardDuration: 5,
    consistencyStrength: 87,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['sora2', 'hubagi-TC-GV'],
  },
  {
    key: 'pet-healing',
    label: '萌宠治愈',
    desc: '适合宠物日常、陪伴叙事、轻喜剧和温暖短视频。',
    tags: ['萌宠', '治愈', '日常'],
    keywords: ['宠物', '小猫', '小狗', '萌宠', '陪伴', '治愈', '日常', '温馨', '搞笑', '铲屎官'],
    styleTags: ['萌宠', '治愈', '扁平插画', '日系'],
    videoStylePreset: 'warm-healing',
    videoMotionMode: 'gentle',
    storyboardAspectRatio: '9:16',
    storyboardResolution: '1080x1920',
    storyboardDuration: 4,
    consistencyStrength: 74,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['hubagi-voe3.1', 'wan'],
  },
  {
    key: 'short-drama-reversal',
    label: '短剧反转',
    desc: '适合冲突密集、爽点前置、结尾留钩子的竖屏短剧。',
    tags: ['短剧', '反转', '爆点'],
    keywords: ['短剧', '反转', '打脸', '复仇', '豪门', '逆袭', '爽文', '钩子', '竖屏', '高能'],
    styleTags: ['都市夜景', '写实', '韩系', '广告感'],
    videoStylePreset: 'realistic-drama',
    videoMotionMode: 'dynamic',
    storyboardAspectRatio: '9:16',
    storyboardResolution: '1080x1920',
    storyboardDuration: 4,
    consistencyStrength: 85,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['hubagi-voe3.1', 'hubagi-TC-GV'],
  },
  {
    key: 'fairy-tale-family',
    label: '亲子童话',
    desc: '适合儿童故事、寓教于乐、奇幻森林和温暖冒险。',
    tags: ['童话', '亲子', '奇幻'],
    keywords: ['童话', '亲子', '儿童', '森林', '王国', '魔法', '公主', '精灵', '寓言', '冒险'],
    styleTags: ['童话', '水彩', '奇幻', '动漫'],
    videoStylePreset: 'fantasy-dream',
    videoMotionMode: 'gentle',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1280x720',
    storyboardDuration: 5,
    consistencyStrength: 79,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['wan', 'hubagi-TC-GV'],
  },
  {
    key: 'historical-epic',
    label: '历史正剧',
    desc: '适合王朝更替、家国叙事、群像角色与庄重历史氛围。',
    tags: ['历史', '正剧', '家国'],
    keywords: ['历史', '王朝', '将军', '帝国', '朝代', '家国', '史诗', '征战', '城池', '正剧'],
    styleTags: ['历史正剧', '写实', '史诗', '古风'],
    videoStylePreset: 'cinematic-epic',
    videoMotionMode: 'cinematic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1920x1080',
    storyboardDuration: 6,
    consistencyStrength: 88,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['sora2', 'wan'],
  },
  {
    key: 'war-strategy',
    label: '战争策略',
    desc: '适合战场推进、兵团对抗、谋略布局与压迫感镜头。',
    tags: ['战争', '策略', '群像'],
    keywords: ['战争', '战场', '军队', '将领', '突围', '围城', '谋略', '前线', '战役', '兵法'],
    styleTags: ['战争', '史诗', '写实', '黑色电影'],
    videoStylePreset: 'cinematic-epic',
    videoMotionMode: 'dynamic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1920x1080',
    storyboardDuration: 5,
    consistencyStrength: 89,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['sora2', 'hubagi-TC-GV'],
  },
  {
    key: 'female-romance',
    label: '女性成长',
    desc: '适合女性向情感、成长觉醒、关系博弈和细腻情绪表达。',
    tags: ['女性向', '成长', '情感'],
    keywords: ['女性', '成长', '闺蜜', '婚姻', '觉醒', '独立', '情感', '治愈', '关系', '都市女性'],
    styleTags: ['女性向', '韩系', '治愈', '写实'],
    videoStylePreset: 'urban-romance',
    videoMotionMode: 'gentle',
    storyboardAspectRatio: '9:16',
    storyboardResolution: '1080x1920',
    storyboardDuration: 5,
    consistencyStrength: 79,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['hubagi-voe3.1', 'wan'],
  },
  {
    key: 'business-power',
    label: '商战博弈',
    desc: '适合资本竞争、创业逆袭、职场权力和谈判场景。',
    tags: ['商战', '职场', '都市'],
    keywords: ['商战', '资本', '公司', '董事会', '创业', '收购', '投资', '职场', '谈判', '竞争'],
    styleTags: ['商战', '职场', '写实', '都市夜景'],
    videoStylePreset: 'realistic-drama',
    videoMotionMode: 'cinematic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1920x1080',
    storyboardDuration: 5,
    consistencyStrength: 82,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['hubagi-voe3.1', 'sora2'],
  },
  {
    key: 'workplace-light',
    label: '轻职场',
    desc: '适合办公室日常、同事关系、成长蜕变和轻喜剧节奏。',
    tags: ['职场', '轻喜', '现代'],
    keywords: ['职场', '办公室', '同事', '老板', '面试', '升职', '打工人', '工位', '会议', '轻喜剧'],
    styleTags: ['职场', '极简', '韩系', '写实'],
    videoStylePreset: 'warm-healing',
    videoMotionMode: 'gentle',
    storyboardAspectRatio: '9:16',
    storyboardResolution: '1080x1920',
    storyboardDuration: 4,
    consistencyStrength: 73,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['hubagi-voe3.1', 'wan'],
  },
  {
    key: 'zhiguai-folklore',
    label: '志怪传说',
    desc: '适合山野狐妖、民间怪谈、诡谲气氛和东方异闻。',
    tags: ['志怪', '民俗', '奇幻'],
    keywords: ['志怪', '狐妖', '怪谈', '山神', '民俗', '纸人', '祠堂', '异闻', '夜行', '精怪'],
    styleTags: ['志怪', '国潮', '水墨', '惊悚'],
    videoStylePreset: 'guofeng-myth',
    videoMotionMode: 'cinematic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1280x720',
    storyboardDuration: 5,
    consistencyStrength: 84,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['wan', 'sora2'],
  },
  {
    key: 'horror-thriller',
    label: '恐怖惊悚',
    desc: '适合密室、追逃、心理惊吓和暗黑高压场景。',
    tags: ['恐怖', '惊悚', '压迫'],
    keywords: ['恐怖', '鬼', '密室', '追杀', '惊悚', '噩梦', '尖叫', '逃生', '怪物', '诡异'],
    styleTags: ['恐怖', '惊悚', '暗黑奇幻', '黑色电影'],
    videoStylePreset: 'suspense-dark',
    videoMotionMode: 'dynamic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1280x720',
    storyboardDuration: 4,
    consistencyStrength: 86,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['sora2', 'wan'],
  },
  {
    key: 'hard-sci-fi',
    label: '硬核科幻',
    desc: '适合太空任务、AI 伦理、科技危机和理性推演剧情。',
    tags: ['硬科幻', '未来', '科技'],
    keywords: ['硬科幻', '太空', '飞船', '星舰', 'AI', '机器人', '量子', '实验室', '未来科技', '宇宙'],
    styleTags: ['科幻', '机甲', '欧美电影感', '3D渲染'],
    videoStylePreset: 'sci-fi-neon',
    videoMotionMode: 'cinematic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1920x1080',
    storyboardDuration: 6,
    consistencyStrength: 90,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['sora2', 'hubagi-TC-GV'],
  },
  {
    key: 'adventure-expedition',
    label: '探险寻宝',
    desc: '适合遗迹机关、团队远征、丛林沙漠和连续推进冒险。',
    tags: ['探险', '寻宝', '冒险'],
    keywords: ['探险', '寻宝', '遗迹', '机关', '考古', '远征', '丛林', '沙漠', '秘宝', '地图'],
    styleTags: ['探险', '史诗', '写实', '奇幻'],
    videoStylePreset: 'cinematic-epic',
    videoMotionMode: 'dynamic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1920x1080',
    storyboardDuration: 5,
    consistencyStrength: 83,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['wan', 'sora2'],
  },
  {
    key: 'travel-roadmovie',
    label: '旅行公路',
    desc: '适合一路见闻、人物关系变化、风景转场和治愈节奏。',
    tags: ['旅行', '公路片', '疗愈'],
    keywords: ['旅行', '公路', '远方', '旅途', '风景', '露营', '搭车', '城市漫游', '出发', '沿途'],
    styleTags: ['旅行', '疗愈系', '纪录片', '复古胶片'],
    videoStylePreset: 'documentary-natural',
    videoMotionMode: 'gentle',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1920x1080',
    storyboardDuration: 5,
    consistencyStrength: 72,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['hubagi-voe3.1', 'wan'],
  },
  {
    key: 'food-lifestyle',
    label: '美食生活',
    desc: '适合厨房叙事、烟火日常、探店记录和轻松分享内容。',
    tags: ['美食', '生活', '烟火气'],
    keywords: ['美食', '做饭', '厨房', '餐厅', '探店', '甜品', '火锅', '日常', '料理', '下厨'],
    styleTags: ['美食', '广告感', '治愈', '写实'],
    videoStylePreset: 'fashion-commercial',
    videoMotionMode: 'gentle',
    storyboardAspectRatio: '9:16',
    storyboardResolution: '1080x1920',
    storyboardDuration: 4,
    consistencyStrength: 77,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['hubagi-voe3.1', 'hubagi-TC-GV'],
  },
  {
    key: 'sports-competition',
    label: '体育竞技',
    desc: '适合训练、赛事、热血逆袭和团队协作成长。',
    tags: ['体育', '竞技', '热血'],
    keywords: ['体育', '竞技', '比赛', '训练', '冠军', '赛场', '球队', '跑步', '篮球', '足球'],
    styleTags: ['体育', '青春', '写实', '史诗'],
    videoStylePreset: 'comic-dynamic',
    videoMotionMode: 'dynamic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1280x720',
    storyboardDuration: 4,
    consistencyStrength: 80,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['hubagi-TC-GV', 'wan'],
  },
  {
    key: 'children-animation',
    label: '儿童动画',
    desc: '适合低龄启蒙、可爱角色、色彩明快和简单故事推进。',
    tags: ['儿童', '动画', '启蒙'],
    keywords: ['儿童', '动画', '启蒙', '宝宝', '卡通', '早教', '可爱', '小动物', '儿歌', '亲子'],
    styleTags: ['儿童动画', '扁平插画', '童话', '萌宠'],
    videoStylePreset: 'anime',
    videoMotionMode: 'gentle',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1280x720',
    storyboardDuration: 4,
    consistencyStrength: 71,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['wan', 'hubagi-TC-GV'],
  },
  {
    key: 'american-crime',
    label: '美式罪案',
    desc: '适合都市罪案、警探追查、法庭攻防和强节奏美剧叙事。',
    tags: ['美剧', '罪案', '黑色'],
    keywords: ['美剧', '罪案', '警探', 'FBI', '法庭', '连环杀手', '侦破', '纽约', '洛杉矶', 'crime'],
    styleTags: ['美剧感', '黑色电影', '写实', '欧美电影感'],
    videoStylePreset: 'suspense-dark',
    videoMotionMode: 'cinematic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1920x1080',
    storyboardDuration: 5,
    consistencyStrength: 86,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['sora2', 'hubagi-voe3.1'],
  },
  {
    key: 'british-mystery',
    label: '英伦悬疑',
    desc: '适合庄园、古堡、推理对话和克制冷调的英剧气质。',
    tags: ['英伦', '悬疑', '推理'],
    keywords: ['英伦', '庄园', '古堡', '侦探', '推理', '伦敦', '贵族', '迷案', '英剧', '绅士'],
    styleTags: ['英伦', '复古胶片', '悬疑', '北欧冷调'],
    videoStylePreset: 'vintage-film',
    videoMotionMode: 'gentle',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1280x720',
    storyboardDuration: 5,
    consistencyStrength: 82,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['sora2', 'wan'],
  },
  {
    key: 'western-frontier',
    label: '西部荒野',
    desc: '适合牛仔、边境追逐、赏金猎人和荒原决斗。',
    tags: ['西部', '荒野', '冒险'],
    keywords: ['西部', '牛仔', '左轮', '荒野', '边境', '赏金猎人', '酒馆', '马车', '决斗', 'western'],
    styleTags: ['西部片', '欧美电影感', '史诗', '写实'],
    videoStylePreset: 'cinematic-epic',
    videoMotionMode: 'dynamic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1920x1080',
    storyboardDuration: 5,
    consistencyStrength: 84,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['sora2', 'wan'],
  },
  {
    key: 'mafia-family',
    label: '黑帮家族',
    desc: '适合家族势力、地下交易、忠诚背叛和暗黑权力戏。',
    tags: ['黑帮', '家族', '权力'],
    keywords: ['黑帮', '教父', '家族', '地下', '帮派', '忠诚', '背叛', '纽约', '交易', 'mafia'],
    styleTags: ['黑帮', '黑色电影', '欧美电影感', '写实'],
    videoStylePreset: 'realistic-drama',
    videoMotionMode: 'cinematic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1920x1080',
    storyboardDuration: 5,
    consistencyStrength: 85,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['sora2', 'hubagi-voe3.1'],
  },
  {
    key: 'superhero-origin',
    label: '超级英雄',
    desc: '适合起源觉醒、城市危机、团队集结和英雄对决。',
    tags: ['超级英雄', '都市', '动作'],
    keywords: ['超级英雄', '英雄', '觉醒', '超能力', '反派', '城市危机', '联盟', '拯救世界', 'hero', 'mutant'],
    styleTags: ['超级英雄', '欧美电影感', '科幻', '3D渲染'],
    videoStylePreset: 'cinematic-epic',
    videoMotionMode: 'dynamic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1920x1080',
    storyboardDuration: 5,
    consistencyStrength: 88,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['sora2', 'hubagi-TC-GV'],
  },
  {
    key: 'vampire-gothic',
    label: '吸血鬼哥特',
    desc: '适合古堡夜宴、永生宿命、禁忌爱情和暗黑美学。',
    tags: ['吸血鬼', '哥特', '暗黑'],
    keywords: ['吸血鬼', '古堡', '永生', '血族', '夜宴', '哥特', '禁忌', '伯爵', 'vampire', 'gothic'],
    styleTags: ['吸血鬼', '哥特', '暗黑奇幻', '欧美电影感'],
    videoStylePreset: 'suspense-dark',
    videoMotionMode: 'gentle',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1280x720',
    storyboardDuration: 5,
    consistencyStrength: 83,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['sora2', 'wan'],
  },
  {
    key: 'werewolf-dark',
    label: '狼人暗夜',
    desc: '适合月夜变身、族群冲突、猎杀追逐和暗黑奇幻叙事。',
    tags: ['狼人', '暗黑', '奇幻'],
    keywords: ['狼人', '月圆', '变身', '猎人', '狼群', '诅咒', '夜林', 'werewolf', 'pack', 'dark fantasy'],
    styleTags: ['狼人', '暗黑奇幻', '恐怖', '欧美电影感'],
    videoStylePreset: 'suspense-dark',
    videoMotionMode: 'dynamic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1280x720',
    storyboardDuration: 4,
    consistencyStrength: 84,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['sora2', 'wan'],
  },
  {
    key: 'magic-academy',
    label: '魔法学院',
    desc: '适合学院成长、社团对抗、天赋觉醒和欧美奇幻青春。',
    tags: ['学院', '魔法', '成长'],
    keywords: ['魔法学院', '学院', '巫师', '法杖', '宿舍', '新生', '魔法课', '校长', 'wizard', 'academy'],
    styleTags: ['魔法学院', '奇幻', '英伦', '欧美电影感'],
    videoStylePreset: 'fantasy-dream',
    videoMotionMode: 'cinematic',
    storyboardAspectRatio: '16:9',
    storyboardResolution: '1280x720',
    storyboardDuration: 5,
    consistencyStrength: 81,
    enableDubbing: true,
    enableSubtitle: true,
    videoMode: 'api_generation',
    preferredVideoRuntimeKeys: ['wan', 'sora2'],
  },
] as const).map((preset) => ({
  ...preset,
  videoStylePreset: normalizeVideoStylePreset(preset.videoStylePreset),
}))

export function summarizePresetTemplate(preset: ProjectPresetTemplate) {
  const primaryRuntime = preset.preferredVideoRuntimeKeys[0] ?? ''
  return [
    { label: '视觉', value: VIDEO_STYLE_PRESET_LABELS[normalizeVideoStylePreset(preset.videoStylePreset)] ?? normalizeVideoStylePreset(preset.videoStylePreset) },
    { label: '模型', value: VIDEO_RUNTIME_KEY_LABELS[primaryRuntime] ?? (primaryRuntime || '自动') },
    { label: '画幅', value: preset.storyboardAspectRatio },
    { label: '运镜', value: VIDEO_MOTION_MODE_LABELS[preset.videoMotionMode] ?? preset.videoMotionMode },
    { label: '时长', value: `${preset.storyboardDuration}s` },
  ]
}

export function buildDraftScriptFileName(title: string, fileName?: string): string {
  if (fileName?.trim()) return fileName.trim()
  const baseName = title.trim() || 'script'
  return `${baseName.replace(/[\\/:*?"<>|]+/g, '_')}.txt`
}

export function recommendPresetTemplate(title: string, description: string, scriptPreview: string): { preset: ProjectPresetTemplate; reason: string } | null {
  const text = `${title} ${description} ${scriptPreview}`.toLowerCase().trim()
  if (!text) return null

  const scored = PROJECT_PRESET_TEMPLATES.map((preset) => {
    const matched = preset.keywords.filter((keyword) => text.includes(keyword.toLowerCase()))
    return { preset, matched }
  }).sort((a, b) => b.matched.length - a.matched.length)

  if (!scored[0] || scored[0].matched.length === 0) return null
  return {
    preset: scored[0].preset,
    reason: `匹配关键词：${scored[0].matched.slice(0, 3).join(' / ')}`,
  }
}
