export const STATUS_MAP: Record<string, { label: string; variant: 'default' | 'secondary' | 'success' | 'warning' | 'destructive' }> = {
  draft: { label: '草稿', variant: 'secondary' },
  script_processing: { label: '剧本解析中', variant: 'default' },
  script_ready: { label: '剧本就绪', variant: 'success' },
  asset_generating: { label: '资源生成中', variant: 'default' },
  asset_ready: { label: '资源就绪', variant: 'success' },
  storyboard_generating: { label: '分镜生成中', variant: 'default' },
  storyboard_ready: { label: '分镜就绪', variant: 'success' },
  video_generating: { label: '视频生成中', variant: 'default' },
  completed: { label: '已完成', variant: 'success' },
  paused: { label: '已暂停', variant: 'warning' },
  failed: { label: '失败', variant: 'destructive' },
  pending: { label: '待处理', variant: 'secondary' },
  processing: { label: '处理中', variant: 'default' },
  succeeded: { label: '已完成', variant: 'success' },
  cancelled: { label: '已取消', variant: 'secondary' },
  generating: { label: '生成中', variant: 'default' },
  done: { label: '已完成', variant: 'success' },
  partial:   { label: '部分完成', variant: 'warning' },
  qa_failed: { label: 'AI质检未通过', variant: 'destructive' },
  scene_splitting: { label: '分镜拆分中', variant: 'default' },
  script_prepping: { label: '剧本优化中', variant: 'default' },
  scene_ready: { label: '分镜就绪', variant: 'success' },
}
